ALL_OUT_PLAYLIST_IDS = ['37i9dQZF1DX5Ejj0EkURtP', '37i9dQZF1DX4o1oenSJRJd', '37i9dQZF1DXbTxeAdrVG2l',
                        '37i9dQZF1DX4UtSsGT1Sbe']
LYRICS_TABLE_NAME = 'Lyrics'
SENTIMENT_TABLE_NAME = 'Sentiments'
PHRASES_TABLE_NAME = 'Phrases'
TOKENS_TABLE_NAME = 'Tokens'
